name: monorepo sample

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      app1: ${{ steps.filter.outputs.app1 }}
      app2: ${{ steps.filter.outputs.app2 }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            app1:
              - 'app1/**'
            app2:
              - 'app2/**'
  app1:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.app1 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "do app1 job"

  app2:
    runs-on: ubuntu-latest
    needs: check-changes
    if: ${{ needs.check-changes.outputs.app2 == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "do app2 job"
